% ode rhs f
F.f=@(x,theta,u) [...
-(-10.0+x(1)+x(2))*exp(theta(3))-x(1)*exp(theta(1))-x(1)*exp(theta(2))*u(1);...
-exp(theta(4))*x(2)+x(1)*exp(theta(1))+x(1)*exp(theta(2))*u(1);...
-exp(theta(5))*(-10.0+x(3))*x(2)-exp(theta(6))*x(3)];
% parameterised model output matrix
F.C=[...
 0.000000  0.000000  98.230000 ];
% Jacobian of f (df/dx)
F.Jf=@(x,theta,u) [...
-exp(theta(1))-exp(theta(2))*u(1)-exp(theta(3)),-exp(theta(3)),0;...
exp(theta(1))+exp(theta(2))*u(1),-exp(theta(4)),0;...
0,-exp(theta(5))*(-10.0+x(3)),-exp(theta(6))-exp(theta(5))*x(2)];
% steady state sensitivity (dx(t→∞,ρ)/dρ)
F.Sf=@(x,theta,u) -[...
-exp(theta(1))-exp(theta(2))*u(1)-exp(theta(3)),-exp(theta(3)),0;...
exp(theta(1))+exp(theta(2))*u(1),-exp(theta(4)),0;...
0,-exp(theta(5))*(-10.0+x(3)),-exp(theta(6))-exp(theta(5))*x(2)]\[...
-x(1)*exp(theta(1)),-x(1)*exp(theta(2))*u(1),-(-10.0+x(1)+x(2))*exp(theta(3)),0,0,0;...
x(1)*exp(theta(1)),x(1)*exp(theta(2))*u(1),0,-exp(theta(4))*x(2),0,0;...
0,0,0,0,-exp(theta(5))*(-10.0+x(3))*x(2),-exp(theta(6))*x(3)];
% model dimensions: number of state variables $n$; number of parameters $m$; number of outputs $l$;
F.n=3;
F.m=6;
F.l=1;
% initial conditions; either constant or function of parameters ρ and inputs u
F.x0=[10;0;0];
% done.% link to second order sensitivity function
F.dSf=@(x,theta,u,Jf,Sf) sensitivity2_Mma(x,theta,u,Jf,Sf);
